name: Arp Personal Assistant
version: 1.0.0
schema: v1

models:
  # - name: Deepseek-R1
  #   provider: ollama
  #   model: deepseek-r1:1.5b
  #   roles: [chat, edit, apply]

  # - name: Qwen2.5-Coder
  #   provider: ollama
  #   model: qwen2.5-coder:1.5b-base
  #   roles: [autocomplete]

  - name: Gemini 2.0 Flash
    provider: gemini
    model: gemini-2.0-flash
    apiKey: GEMINI_API_KEY
    roles: [autocomplete, chat, edit, apply]

  - name: Gemini 2.5 Flash
    provider: gemini
    model: gemini-2.5-flash
    apiKey: GEMINI_API_KEY
    roles: [autocomplete, chat, edit, apply]

  - name: Gemini 2.5 Pro
    provider: gemini
    model: gemini-2.5-pro
    apiKey: GEMINI_API_KEY
    roles: [autocomplete, chat, edit, apply]

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase

tabAutocompleteOptions:
  debounceDelay: 500            # Delay in milliseconds before triggering autocomplete
  maxPromptTokens: 1500         # Max tokens sent in a prompt
  maxSuffixPercentage: 0.2      # % of the suffix included
  prefixPercentage: 0.3         # % of the prefix included
  disableInFiles:
    - "*.md"                    # Prevent autocomplete in markdown files

